In [1]:
from pathlib import Path
import sys

PROJECT_ROOT = Path.cwd().parent

if str(PROJECT_ROOT) not in sys.path:
    sys.path.append(str(PROJECT_ROOT))

In [2]:
from datetime import datetime

from simulation.simulation import Simulation
from simulation.demand_engine import preview_day
import simulation.simulation_config as config

In [3]:
from simulation.simulation import Simulation
from simulation.customer_engine import add_customer_order_weights, select_dealer, select_dtc_customer
from simulation.product_engine import choose_product

In [4]:
sim = Simulation()
sim.load_master_data()
sim.initialize_inventory()

sim.customers = add_customer_order_weights(sim.customers)

In [6]:
from datetime import datetime
import pandas as pd

from simulation.simulation import Simulation
from simulation.customer_engine import add_customer_order_weights
from simulation.order_generator import (
    generate_dealer_order,
    generate_dtc_order,
    generate_daily_orders,
)

In [7]:
sim = Simulation()
sim.load_master_data()
sim.initialize_inventory()

sim.customers = add_customer_order_weights(sim.customers)

In [8]:
dealer_header, dealer_lines = generate_dealer_order(
    sim,
    datetime(2023, 5, 15),
)

dealer_header

{'sales_order_id': 'SO100000',
 'order_date': '2023-05-15',
 'customer_id': 'C0015',
 'customer_name': 'Sierra Cycle Works',
 'sales_channel': 'Dealer',
 'order_status': 'Booked',
 'payment_terms': 'Net 30',
 'warehouse': 'Phoenix Distribution Center',
 'order_total': 35333.18}

In [9]:
pd.DataFrame(dealer_lines)

,sales_order_id,line_number,product_id,sku,model_name,category,size,color,requested_qty,unit_msrp,discount_pct,unit_price,extended_price,unit_cost,extended_cost,gross_profit
0,SO100000,1,1103,SON-ROM-C-M-IR,Romero,Aggressive Trail,M,Ironwood,5,5199.0,0.38,3223.38,16116.90,3015.42,15077.10,1039.80
1,SO100000,2,1080,SON-SAB-C-L-SG,Sabino,Trail,L,Saguaro,1,4599.0,0.38,2851.38,2851.38,2575.44,2575.44,275.94
2,SO100000,3,1082,SON-SAB-C-L-GR,Sabino,Trail,L,Granite,1,4599.0,0.38,2851.38,2851.38,2575.44,2575.44,275.94
3,SO100000,4,1135,SON-ORA-C-M-SS,Oracle,Enduro,M,Sunset,1,6199.0,0.38,3843.38,3843.38,3719.40,3719.40,123.98
4,SO100000,5,1099,SON-ROM-C-S-SS,Romero,Aggressive Trail,S,Sunset,3,5199.0,0.38,3223.38,9670.14,3015.42,9046.26,623.88

In [10]:
dtc_header, dtc_lines = generate_dtc_order(
    sim,
    datetime(2023, 5, 15),
)

dtc_header

{'sales_order_id': 'SO100001',
 'order_date': '2023-05-15',
 'customer_id': 'C0001',
 'customer_name': 'Sonoran Cycles Online',
 'sales_channel': 'DTC',
 'order_status': 'Booked',
 'payment_terms': 'Credit Card',
 'warehouse': 'Phoenix Distribution Center',
 'order_total': 3299.0}

In [11]:
pd.DataFrame(dtc_lines)

,sales_order_id,line_number,product_id,sku,model_name,category,size,color,requested_qty,unit_msrp,discount_pct,unit_price,extended_price,unit_cost,extended_cost,gross_profit
0,SO100001,1,1006,SON-CAT-C-XS-SK,Catalina,Cross Country,XS,Sky,1,3299.0,0.0,3299.0,3299.0,1748.47,1748.47,1550.53

In [12]:
daily_summary = generate_daily_orders(
    sim,
    datetime(2023, 5, 15),
    "Sunny",
)

daily_summary

{'date': '2023-05-15',
 'weather': 'Sunny',
 'dealer_orders': 26,
 'dtc_orders': 14,
 'total_orders': 40}

In [13]:
pd.DataFrame(sim.sales_orders).head()

,sales_order_id,order_date,customer_id,customer_name,sales_channel,order_status,payment_terms,warehouse,order_total
0,SO100000,2023-05-15,C0015,Sierra Cycle Works,Dealer,Booked,Net 30,Phoenix Distribution Center,35333.18
1,SO100001,2023-05-15,C0001,Sonoran Cycles Online,DTC,Booked,Credit Card,Phoenix Distribution Center,3299.00
2,SO100002,2023-05-15,C0026,Great Lakes Cyclery,Dealer,Booked,Net 30,Phoenix Distribution Center,16571.10
3,SO100003,2023-05-15,C0031,Pisgah Bike Co.,Dealer,Booked,Net 45,Phoenix Distribution Center,14381.68
4,SO100004,2023-05-15,C0036,Pine Tree Bicycles,Dealer,Booked,Net 30,Phoenix Distribution Center,18001.10

In [14]:
pd.DataFrame(sim.sales_order_lines).head()

,sales_order_id,line_number,product_id,sku,model_name,category,size,color,requested_qty,unit_msrp,discount_pct,unit_price,extended_price,unit_cost,extended_cost,gross_profit
0,SO100000,1,1103,SON-ROM-C-M-IR,Romero,Aggressive Trail,M,Ironwood,5,5199.0,0.38,3223.38,16116.90,3015.42,15077.10,1039.80
1,SO100000,2,1080,SON-SAB-C-L-SG,Sabino,Trail,L,Saguaro,1,4599.0,0.38,2851.38,2851.38,2575.44,2575.44,275.94
2,SO100000,3,1082,SON-SAB-C-L-GR,Sabino,Trail,L,Granite,1,4599.0,0.38,2851.38,2851.38,2575.44,2575.44,275.94
3,SO100000,4,1135,SON-ORA-C-M-SS,Oracle,Enduro,M,Sunset,1,6199.0,0.38,3843.38,3843.38,3719.40,3719.40,123.98
4,SO100000,5,1099,SON-ROM-C-S-SS,Romero,Aggressive Trail,S,Sunset,3,5199.0,0.38,3223.38,9670.14,3015.42,9046.26,623.88