In [1]:
from pathlib import Path
import sys

PROJECT_ROOT = Path.cwd().parent

if str(PROJECT_ROOT) not in sys.path:
    sys.path.append(str(PROJECT_ROOT))

In [2]:
from datetime import datetime

from simulation.simulation import Simulation
from simulation.demand_engine import preview_day
import simulation.simulation_config as config

In [3]:
from simulation.simulation import Simulation
from simulation.customer_engine import add_customer_order_weights, select_dealer, select_dtc_customer
from simulation.product_engine import choose_product

In [4]:
sim = Simulation()
sim.load_master_data()
sim.initialize_inventory()

sim.customers = add_customer_order_weights(sim.customers)

In [5]:
from datetime import datetime
import pandas as pd

from simulation.simulation import Simulation
from simulation.customer_engine import add_customer_order_weights
from simulation.order_generator import (
    generate_dealer_order,
    generate_dtc_order,
    generate_daily_orders,
)

In [6]:
sim = Simulation()
sim.load_master_data()
sim.initialize_inventory()

sim.customers = add_customer_order_weights(sim.customers)

In [7]:
dealer_header, dealer_lines = generate_dealer_order(
    sim,
    datetime(2023, 5, 15),
)

dealer_header

{'sales_order_id': 'SO100000',
 'order_date': '2023-05-15',
 'customer_id': 'C0016',
 'customer_name': 'Coastal Gravel Co.',
 'sales_channel': 'Dealer',
 'order_status': 'Booked',
 'payment_terms': 'Net 30',
 'warehouse': 'Phoenix Distribution Center',
 'order_total': 20340.45}

In [8]:
pd.DataFrame(dealer_lines)

,sales_order_id,line_number,product_id,sku,model_name,category,size,color,requested_qty,unit_msrp,discount_pct,unit_price,extended_price,unit_cost,extended_cost,gross_profit
0,SO100000,1,1112,SON-ROM-C-L-GR,Romero,Aggressive Trail,L,Granite,4,5199.0,0.35,3379.35,13517.40,3015.42,12061.68,1455.72
1,SO100000,2,1196,SON-SON-A-M-GR,Sonoita,Gravel,M,Granite,3,3499.0,0.35,2274.35,6823.05,1819.48,5458.44,1364.61

In [9]:
dtc_header, dtc_lines = generate_dtc_order(
    sim,
    datetime(2023, 5, 15),
)

dtc_header

{'sales_order_id': 'SO100001',
 'order_date': '2023-05-15',
 'customer_id': 'C0001',
 'customer_name': 'Sonoran Cycles Online',
 'sales_channel': 'DTC',
 'order_status': 'Booked',
 'payment_terms': 'Credit Card',
 'warehouse': 'Phoenix Distribution Center',
 'order_total': 3999.0}

In [10]:
pd.DataFrame(dtc_lines)

,sales_order_id,line_number,product_id,sku,model_name,category,size,color,requested_qty,unit_msrp,discount_pct,unit_price,extended_price,unit_cost,extended_cost,gross_profit
0,SO100001,1,1043,SON-RIN-C-M-IR,Rincon,Downcountry,M,Ironwood,1,3999.0,0.0,3999.0,3999.0,2199.45,2199.45,1799.55

In [11]:
daily_summary = generate_daily_orders(
    sim,
    datetime(2023, 5, 15),
    "Sunny",
)

daily_summary

{'date': '2023-05-15',
 'weather': 'Sunny',
 'dealer_orders': 29,
 'dtc_orders': 12,
 'total_orders': 41}

In [12]:
pd.DataFrame(sim.sales_orders).head()

,sales_order_id,order_date,customer_id,customer_name,sales_channel,order_status,payment_terms,warehouse,order_total
0,SO100000,2023-05-15,C0016,Coastal Gravel Co.,Dealer,Booked,Net 30,Phoenix Distribution Center,20340.45
1,SO100001,2023-05-15,C0001,Sonoran Cycles Online,DTC,Booked,Credit Card,Phoenix Distribution Center,3999.00
2,SO100002,2023-05-15,C0033,Appalachian Bikes,Dealer,Booked,Net 30,Phoenix Distribution Center,21075.66
3,SO100003,2023-05-15,C0004,Sonoran Bike Co.,Dealer,Booked,Net 30,Phoenix Distribution Center,50830.08
4,SO100004,2023-05-15,C0010,Evergreen Cyclery,Dealer,Booked,Net 45,Phoenix Distribution Center,22671.62

In [13]:
pd.DataFrame(sim.sales_order_lines).head()

,sales_order_id,line_number,product_id,sku,model_name,category,size,color,requested_qty,unit_msrp,discount_pct,unit_price,extended_price,unit_cost,extended_cost,gross_profit
0,SO100000,1,1112,SON-ROM-C-L-GR,Romero,Aggressive Trail,L,Granite,4,5199.0,0.35,3379.35,13517.40,3015.42,12061.68,1455.72
1,SO100000,2,1196,SON-SON-A-M-GR,Sonoita,Gravel,M,Granite,3,3499.0,0.35,2274.35,6823.05,1819.48,5458.44,1364.61
2,SO100001,1,1043,SON-RIN-C-M-IR,Rincon,Downcountry,M,Ironwood,1,3999.0,0.00,3999.00,3999.00,2199.45,2199.45,1799.55
3,SO100002,1,1116,SON-ROM-C-XL-SG,Romero,Aggressive Trail,XL,Saguaro,3,5199.0,0.38,3223.38,9670.14,3015.42,9046.26,623.88
4,SO100002,2,1083,SON-SAB-C-L-CY,Sabino,Trail,L,Coyote,4,4599.0,0.38,2851.38,11405.52,2575.44,10301.76,1103.76

In [14]:
print("Sales orders:", len(sim.sales_orders))
print("Sales order lines:", len(sim.sales_order_lines))

Sales orders: 43
Sales order lines: 150

In [15]:
import pandas as pd

from simulation.simulation import Simulation
from simulation.simulation_runner import run_sales_simulation

In [16]:
sim = Simulation()
sim.load_master_data()
sim.initialize_inventory()

In [17]:
daily_summary = run_sales_simulation(
    sim,
    start_date="2023-05-01",
    end_date="2023-05-07",
)

In [18]:
pd.DataFrame(daily_summary)

         date weather  dealer_orders  dtc_orders  total_orders
0  2023-05-01   Sunny             29          13            42
1  2023-05-02   Sunny             31          11            42
2  2023-05-03   Sunny             28          12            40
3  2023-05-04   Sunny             24          15            39
4  2023-05-05   Sunny             20          17            37
5  2023-05-06   Sunny              8          18            26
6  2023-05-07   Sunny              2          19            21

In [19]:
pd.DataFrame(sim.sales_orders).head()

,sales_order_id,order_date,customer_id,customer_name,sales_channel,order_status,payment_terms,warehouse,order_total
0,SO100000,2023-05-01,C0025,Lakeshore Bikes,Dealer,Booked,Net 30,Phoenix Distribution Center,12892.28
1,SO100001,2023-05-01,C0018,High Country Bikes,Dealer,Booked,Net 45,Phoenix Distribution Center,15656.52
2,SO100002,2023-05-01,C0002,Desert Trail Bikes,Dealer,Booked,Net 45,Phoenix Distribution Center,17628.52
3,SO100003,2023-05-01,C0010,Evergreen Cyclery,Dealer,Booked,Net 45,Phoenix Distribution Center,21049.36
4,SO100004,2023-05-01,C0016,Coastal Gravel Co.,Dealer,Booked,Net 30,Phoenix Distribution Center,11371.75

In [20]:
pd.DataFrame(sim.sales_order_lines).head()

,sales_order_id,line_number,product_id,sku,model_name,category,size,color,requested_qty,unit_msrp,discount_pct,unit_price,extended_price,unit_cost,extended_cost,gross_profit
0,SO100000,1,1016,SON-CAT-C-M-GR,Catalina,Cross Country,M,Granite,1,3299.0,0.38,2045.38,2045.38,1748.47,1748.47,296.91
1,SO100000,2,1188,SON-SON-A-S-SG,Sonoita,Gravel,S,Saguaro,5,3499.0,0.38,2169.38,10846.90,1819.48,9097.40,1749.50
2,SO100001,1,1073,SON-SAB-C-M-IR,Sabino,Trail,M,Ironwood,3,4599.0,0.42,2667.42,8002.26,2575.44,7726.32,275.94
3,SO100001,2,1100,SON-ROM-C-S-GR,Romero,Aggressive Trail,S,Granite,1,5199.0,0.42,3015.42,3015.42,3015.42,3015.42,0.00
4,SO100001,3,1041,SON-RIN-C-S-CY,Rincon,Downcountry,S,Coyote,2,3999.0,0.42,2319.42,4638.84,2199.45,4398.90,239.94

In [21]:
print("Sales orders:", len(sim.sales_orders))
print("Sales order lines:", len(sim.sales_order_lines))

Sales orders: 247
Sales order lines: 695

In [22]:
orders_df = pd.DataFrame(sim.sales_orders)
lines_df = pd.DataFrame(sim.sales_order_lines)

header_totals = orders_df.set_index("sales_order_id")["order_total"]
line_totals = lines_df.groupby("sales_order_id")["extended_price"].sum()

max_difference = (
    header_totals.round(2) - line_totals.round(2)
).abs().max()

max_difference

0.0

In [ ]:
sim = Simulation()
sim.load_master_data()
sim.initialize_inventory()

daily_summary = run_sales_simulation(
    sim,
    start_date="2023-01-01",
    end_date="2023-12-31",
)

print("Sales orders:", len(sim.sales_orders))
print("Sales order lines:", len(sim.sales_order_lines))